version: "2"
services:
  app:
    build: ./my-project
    links:
      - db
    ports:
      - "5000:80"
  db:
     image: mysql:5.7
     ports:
        - "3306:3306"
     environment:
             MYSQL_ROOT_PASSWORD: root
     volumes:
             - ./db:/docker-entrypoint-initdb.d/:ro
